# Generated by Django 3.1.3 on 2020-11-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование основной категории')),
            ],
            options={
                'verbose_name': 'Основная категория',
                'verbose_name_plural': 'Основные категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('title_en', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_en', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('photo', models.ImageField(blank=True, upload_to='photo_work/%Y/%m/%d/', verbose_name='Фото')),
                ('is_published', models.BooleanField(default='True', verbose_name='Публиковать?')),
                ('password', models.CharField(blank=True, max_length=8)),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maincategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='noteapp.maincategory')),
                ('note', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='noteapp.note')),
            ],
        ),
    ]
