# Generated by Django 3.1.3 on 2020-12-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='nonce1',
            field=models.TextField(blank=True, verbose_name='nonce_контент'),
        ),
        migrations.AlterField(
            model_name='note',
            name='nonce2',
            field=models.TextField(blank=True, verbose_name='nonce_заголовок'),
        ),
        migrations.AlterField(
            model_name='note',
            name='salt1',
            field=models.TextField(blank=True, verbose_name='Salt_контент'),
        ),
        migrations.AlterField(
            model_name='note',
            name='salt2',
            field=models.TextField(blank=True, verbose_name='Salt_заголовок'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag1',
            field=models.TextField(blank=True, verbose_name='tag_контент'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tag2',
            field=models.TextField(blank=True, verbose_name='tag_заголовок'),
        ),
    ]
