# Generated by Django 3.1.3 on 2020-11-29 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_auto_20201129_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='noteapp.category'),
        ),
    ]
