# Generated by Django 3.1.3 on 2020-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_auto_20201211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
